config/routes.rb
Rails.application.routes.draw do
  resources :dealers

  root 'dealers#index'

end

app/models/dealer.rb
class Dealer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dealers_controller.rb
class DealersController < ApplicationController
  before_action :set_dealer, only: [:show, :edit, :update, :destroy]

  # GET /dealers
  # GET /dealers.json
  def index
    @dealers = Dealer.all
  end

  # GET /dealers/1
  # GET /dealers/1.json
  def show
  end

  # GET /dealers/new
  def new
    @dealer = Dealer.new
  end

  # GET /dealers/1/edit
  def edit
  end

  # POST /dealers
  # POST /dealers.json
  def create
    @dealer = Dealer.new(dealer_params)

    respond_to do |format|
      if @dealer.save
        format.html { redirect_to @dealer, notice: 'Dealer was successfully created.' }
        format.json { render :show, status: :created, location: @dealer }
      else
        format.html { render :new }
        format.json { render json: @dealer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dealers/1
  # PATCH/PUT /dealers/1.json
  def update
    respond_to do |format|
      if @dealer.update(dealer_params)
        format.html { redirect_to @dealer, notice: 'Dealer was successfully updated.' }
        format.json { render :show, status: :ok, location: @dealer }
      else
        format.html { render :edit }
        format.json { render json: @dealer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealers/1
  # DELETE /dealers/1.json
  def destroy
    @dealer.destroy
    respond_to do |format|
      format.html { redirect_to dealers_url, notice: 'Dealer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealer
      @dealer = Dealer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dealer_params
      params.require(:dealer).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dealers_helper.rb
module DealersHelper
end

app/views/dealers/_form.html.erb
<%= form_for(@dealer) do |f| %>
  <% if @dealer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dealer.errors.count, "error") %> prohibited this dealer from being saved:</h2>

      <ul>
      <% @dealer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dealers/edit.html.erb
<h1>Editing Dealer</h1>

<%= render 'form' %>

<%= link_to 'Show', @dealer %> |
<%= link_to 'Back', dealers_path %>

app/views/dealers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dealers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dealers.each do |dealer| %>
      <tr>
        <td><%= dealer.name %></td>
        <td><%= link_to 'Show', dealer %></td>
        <td><%= link_to 'Edit', edit_dealer_path(dealer) %></td>
        <td><%= link_to 'Destroy', dealer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dealer', new_dealer_path %>

app/views/dealers/new.html.erb
<h1>New Dealer</h1>

<%= render 'form' %>

<%= link_to 'Back', dealers_path %>

app/views/dealers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dealer.name %>
</p>

<%= link_to 'Edit', edit_dealer_path(@dealer) %> |
<%= link_to 'Back', dealers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vagrant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>